# NOTE: All files being used in this program are assumed to be in the same directory with this script,should you have your files elsewhere , you'll need to add the full file path.

# Required packages for Excel reading + XML handling
packages <- c("readxl", "xml2", "dplyr") 

for(p in packages){
  # Try to load the package to see if installed 
  if(!require(p, character.only = TRUE)){ 
    install.packages(p)  # install package only if unavailable
    library(p, character.only = TRUE)  # load package after installing
  }
}

# -----------------------------
# 1.Read the source of literal questions (assuming this is an ODK xlsx form , read the survey sheet;making sure var_name maps to column "name" and literal_question maps to column "label")
# -----------------------------
survey_data <- read_excel(
  "Dummy-study-CHOLERA_MW_2024_Questionnaire_ODK.xlsx",# add what applies in your case 
  sheet = "survey"
)

survey_questions <- survey_data %>%
  select(name, label) %>%
  filter(!is.na(name), !is.na(label))

survey_questions$name <- trimws(tolower(survey_questions$name))

# -----------------------------
# 2. Read XML generated by Metadata Editor 
# -----------------------------
ddi_xml <- read_xml("study_Qs.xml")

# Detect XML namespaces to prevent XML namespace look-up failure.
ns <- xml_ns(ddi_xml)
prefix <- names(ns)[1]

# -----------------------------
# 3. Find vars(variables) 
# -----------------------------
vars <- xml_find_all(ddi_xml, paste0(".//", prefix, ":var"), ns)

cat("Vars found:", length(vars), "\n")

updated_count <- 0

# -----------------------------
# 4. Loop through variables
# -----------------------------
for (v in vars) {
  
  var_name <- xml_attr(v, "name")
  
  if (!is.na(var_name)) {
    
    var_name_clean <- trimws(tolower(var_name))
    
    question_match <- survey_questions %>%
      filter(name == var_name_clean)
    
    if (nrow(question_match) == 1) {
      
      literal_question <- question_match$label
      
      # remove any existing qstn  (to avoid wrong placement)
      old_qstn <- xml_find_first(v, paste0("./", prefix, ":qstn"), ns)
      if (!is.na(old_qstn)) {
        xml_remove(old_qstn)
      }
      
      # find labl node
      labl_node <- xml_find_first(v, paste0("./", prefix, ":labl"), ns)
      
      if (!is.na(labl_node)) {
        
        # create qstn node
        qstn_node <- xml_add_sibling(labl_node, "qstn", .where = "after")
        
        # add qstnLit inside it
        xml_add_child(qstn_node, "qstnLit", literal_question)
        
        updated_count <- updated_count + 1
      }
    }
  }
}

# -----------------------------
# 5. Export the XML for importing into Metadata Editor 
# -----------------------------
write_xml(ddi_xml, "study_Qs_question_filled.xml") # add what applies in your case 

cat("Vars updated:", updated_count, "\n")